name: Publish
on:
  push:
    branches:
      - "release"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      issues: write
      contents: write
      pull-requests: write
    steps:

      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}